function d_Y = nnamm_velocity_vector(Y, q_mu, param)
SE = sigmoid( ...
    Y(param.ode(:, [9, 9, 13, 9, 9, 9])), ...
    param.SE_max, param.SE_rate, param.SE_mode, param.SE_off);
SE(:, 6) = param.Omega_Ast * SE(:, 6);

SN = sigmoid( ...
    [SE(:, 1) - SE(:, 3) + Y(param.ode(:, 2)) - Y(param.ode(:, 3)), ...
    param.C_Pyr_to_ExIn .* Y(param.ode(:, 1)), ...
    SE(:, 2) + param.C_Pyr_to_InIn .* Y(param.ode(:, 1))], ...
    param.SN_max, param.SN_rate, param.SN_mode, param.SN_off);

MM = mich_menten_kin(Y(param.ode(:, [13, 13])), param.MM_v_max, param.MM_K);

d_Y = [ ...
    ... % E_Pyr
    Y(param.ode(:, 4)); ...
    ... % E_ExIn_and_Pyr
    Y(param.ode(:, 5)); ...
    ... % E_InIn
    Y(param.ode(:, 6)); ...
    ... % d[E_Pyr]
    param.a .* (param.A .* SN(:, 1) - 2 * Y(param.ode(:, 4)) - param.a .* Y( ...
    param.ode(:, 1))); ...
    ... % d[E_ExIn_and_Pyr]
    param.a .* (param.A .* (q_mu + param.Omega_Pyr * SN(:, 1) + ...
    param.C_Pyr_to_Pyr .* SN(:, 1) + param.C_ExIn_to_Pyr .* SN(:, 2)) - 2 * Y( ...
    param.ode(:, 5)) - param.a .* Y(param.ode(:, 2))); ...
    ... % d[E_InIn]
    param.b .* (param.B .* param.C_InIn_to_Pyr .* SN(:, 3) - 2 * Y(param.ode(:, ...
    6)) - param.b .* Y(param.ode(:, 3))); ...
    ... % J_Glu
    Y(param.ode(:, 8)); ...
    ... % d[J_Glu]
    param.W_Ast .* SE(:, 6) + param.W_Pyr .* SN(:, 1) - param.w_s .* Y( ...
    param.ode(:, 8)) - param.w_p .* Y(param.ode(:, 7)); ...
    ... % Glu_e
    Y(param.ode(:, 7)) - SE(:, 4) - SE(:, 5); ...
    ... % Glu_Ast
    SE(:, 4) - Y(param.ode(:, 10)) ./ param.tau_Glu_Ast; ...
    ... % J_GABA
    Y(param.ode(:, 12)); ...
    ... % d[J_GABA]
    param.Z_Ast .* SE(:, 6) + param.Z_InIn .* SN(:, 3) - param.z_s .* Y( ...
    param.ode(:, 12)) - param.z_p .* Y(param.ode(:, 11)); ...
    ... % GABA_e
    Y(param.ode(:, 11)) - MM(:, 1) - MM(:, 2); ...
    ... % GABA_Ast
    MM(:, 1) - Y(param.ode(:, 14)) ./ param.tau_GABA_Ast; ...
    ];
end
